
'''ARREGLOS UNDIMENSIONALES(OPERCIONES BASICAS)'''

#FORMA DE CREACIÓN
A=[1,2,3,4,5]
B=["hola",10,False,55]
print("Arreglo A:", A)
print("Arreglo B:", B)
print("-"*30) #SEPARADOR PARA MEJOR VISUALIZACIÓN

#SEGUNDA FORMA DE CREACIÓN
C=list([6,7,8,9,10])
D=list([]) #ARREGLO VACIO
print("Arreglo C:", C)
print("Arreglo D:", D)
print("-"*30) #SEPARADOR PARA MEJOR VISUALIZACIÓN

#TERCERA FORMA DE CREACION
E=[0]*3
E[0]=11
E[1]=12
E[2]=13
print("Arreglo E:", E)
print("-"*30) #SEPARADOR PARA MEJOR VISUALIZACIÓN

#ACCESO A ELEMENTOS
ELEMENTO=A[0] #ACEEDIENDO AL ELEMENTO QUE SE ENCUENTRE EN EL INDICE CERO.
print("El elemento del arreglo A:", ELEMENTO)
print("-"*30) #SEPARADOR PARA MEJOR VISUALIZACIÓN

#LONGITUD DEL ARREGLO
LONGITUD=len(B)
print("El tamaño del arreglo B:", LONGITUD)
print("-"*30) #SEPARADOR PARA MEJOR VISUALIZACIÓN

#MODIFICAR ELEMENTOS
E[1]=15
print("ARREGLO E:",E)
print("-"*30) #SEPARADOR PARA MEJOR VISUALIZACIÓN

#INSERTAR ELEMENTOS EN POSICIONES ESPECIFICAS
D.insert(0,"Nuevo") #INSERTANDO ELEMENTOS
print("ARREGLO D:",D)
print("-"*30) #SEPARADOR PARA MEJOR VISUALIZACIÓN

#INSERTAR ELEMENTOS AL FINAL
D.append(25)
print("ARREGLO D:",D)
print("-"*30) #SEPARADOR PARA MEJOR VISUALIZACIÓN

#INSERTAR VARIOS ELEMENTOS AL FINAL
C.extend([20,30,40,50])
print("Arreglo C:", C)
print("-"*30) #SEPARADOR PARA MEJOR VISUALIZACIÓN

#ELIMINAR ELEMENTOS POR INDICE
del B[1]
print("Arreglo B:", B)
print("-"*30) #SEPARADOR PARA MEJOR VISUALIZACIÓN

#ELIMINAR ELEMENTOS AL FINAL
del A[4]
print("Arreglo A:", A)
print("-"*30) #SEPARADOR PARA MEJOR VISUALIZACIÓN

#ELIMINAR ELEMENTOS POR VALOR 
A.remove(1)
print("Arreglo A:", A)
print("-"*30) #SEPARADOR PARA MEJOR VISUALIZACIÓN

#ELIMINAR ELEMENTO Y DEVOLVER 
ELEMENTOELIMINADO=C.pop(2)
print("Arreglo C:", C)
print("El elemento eliminado es:",ELEMENTOELIMINADO)
print("-"*30) #SEPARADOR PARA MEJOR VISUALIZACIÓN